name: Deploy to Production

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create_and_upload_artifact:
    name: Create and Upload Artifact
    runs-on: ubuntu-latest
    environment: CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Artifact
      run: find . -not -path '*/\.*' -type f -print | zip -r app.zip -@

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app.zip

  deploy:
    name: Deploy Artifact to PythonAnywhere
    runs-on: ubuntu-latest
    environment: CI/CD

    needs: [create_and_upload_artifact]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: app
        path: app.zip

    - name: Deploy Artifact
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        python3 .github/workflows/upload_artifact.py "${PA_USERNAME}" "${PA_API_TOKEN}" "app.zip"

    # Optionally, add steps for additional deployment actions like reloading web app
    # - name: Reload Web App
    #   env:
    #     PA_BASE_URL: ${{ secrets.PA_BASE_URL }}
    #     PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
    #     PA_USERNAME: ${{ secrets.PA_USERNAME }}
    #   run: |
    #     curl -X POST "${PA_BASE_URL}/api/v0/user/${PA_USERNAME}/webapps/vendorverse.eu.pythonanywhere.com/reload/" \
    #          -H "Authorization: Token ${PA_API_TOKEN}"
