name: Deploy to PythonAnywhere

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Create Artifact and Deploy
    runs-on: ubuntu-latest
    environment: CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create artifact
      run: |
        zip -r content.zip * .[^.]* 

    - name: Upload Artifact
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: python3 .github/workflows/upload_artifact.py ${PA_USERNAME} ${PA_API_TOKEN} "content.zip"

    - name: Setup Prod Environment
      env:
        PA_BASE_URL: ${{ vars.PA_BASE_URL }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: |

        # Unzip the file, recreate venv, install dependencies, and clean up
        curl -X POST "${PA_BASE_URL}/api/v0/user/${PA_USERNAME}/consoles/" \
             -H "Authorization: Token ${PA_API_TOKEN}" \
             -d "command=bash -c 'cd /home/${PA_USERNAME} && unzip -o content.zip && rm content.zip && python3 -m venv VendorVerseProd && source VendorVerseProd/bin/activate && pip install -r requirements.txt'"

    - name: Reload Web App
      env:
        PA_BASE_URL: ${{ vars.PA_BASE_URL }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}

      run: |
        curl -X POST "${PA_BASE_URL}/api/v0/user/${PA_USERNAME}/webapps/vendorverse.eu.pythonanywhere.com/reload/" \
             -H "Authorization: Token ${PA_API_TOKEN}"
       
