name: Deploy to PythonAnywhere

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Create Artifact and Deploy
    runs-on: ubuntu-latest
    environment: CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create artifact
      run: |
        zip -r content.zip * .[^.]* 

    - name: Upload Artifact
      env:
        PA_BASE_URL: ${{ vars.PA_BASE_URL }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: |
          python3 - << EOF
          import requests
          import os

          upload_url = f"{os.getenv('PA_BASE_URL')}/api/v0/user/{os.getenv('PA_USERNAME')}/files/path/home/{os.getenv('PA_USERNAME')}/content.zip"

          # Upload the zip file
          with open('content.zip', 'rb') as file:
              headers = {'Authorization': f'Token {os.getenv('PA_API_TOKEN')}'}
              response = requests.post(upload_url, headers=headers, files={'content': file})
              response.raise_for_status()
              print('File uploaded successfully.')
          EOF

    - name: Restart Web App
      env:
        PA_BASE_URL: ${{ vars.PA_BASE_URL }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: |

        # Unzip the file, recreate venv, install dependencies, and clean up
        curl -X POST "${PA_BASE_URL}/api/v0/user/${PA_USERNAME}/consoles/" \
             -H "Authorization: Token ${PA_API_TOKEN}" \
             -d "command=bash -c 'cd ~ && unzip -o app.zip && rm app.zip && python3 -m venv VendorVerseProd && source venv/bin/activate && pip install -r requirements.txt'"

        # Reload the web app
        curl -X POST "${PA_BASE_URL}/api/v0/user/${PA_USERNAME}/webapps/vendorverse.eu.pythonanywhere.com/reload/" \
             -H "Authorization: Token ${PA_API_TOKEN}"
       
