name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s tests

  sonarcloud:
    name: Upload to SonarCloud
    runs-on: ubuntu-latest
    environment: CI/CD
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: SonarSource/sonarcloud-github-action@master

  get-coverage:
    name: Code Coverage Report
    runs-on: ubuntu-latest
    needs: [sonarcloud]
    outputs:
      coverage: ${{ steps.get-coverage.outputs.coverage }}
    steps:
    - name: Get code coverage percentage
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
      run: |
        sudo apt-get install -y jq
        ANALYSIS_URL="https://sonarcloud.io/api/measures/component?component=BALLDN_VendorVerse&metricKeys=coverage"
        COVERAGE=$(curl -s "$ANALYSIS_URL" -H "Authorization: Bearer ${SONAR_TOKEN}" | jq -r '.component.measures[0].value')
        echo "Code Coverage: $COVERAGE%"
          
  trigger-deploy:
    name: Trigger Deploy
    runs-on: ubuntu-latest
    needs: [run-tests, get-coverage]

    # if: needs.get-coverage.outputs.coverage > 80.0
    steps:
      - uses: ./.github/workflows/deploy.yml
